version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  node:
    container_name: node_${APP_NAME}
    image: node_${APP_NAME}
    build:
      context: docker/node
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 3000:3000
    networks:
      - app-network
